[build]
    functions = "lambda"

[template.environment]
    CHATKIT_INSTANCE_LOCATOR = "Chatkit instance locator"
    CHATKIT_KEY = "Chatkit key"
    AUTH0_DOMAIN = "Auth0 domain"
    AUTH0_CLIENT_ID = "Auth0 client ID"
    AUTH0_CLIENT_SECRET = "Auth0 client secret"


